const translations = {
    "tr": {
        "navHome": "Anasayfa",
        "navServices": "Hizmetler",
        "navProjects": "Projeler",
        "navContact": "İletişim",
        "phone": "+90 539 957 1333",
        "heroTitle": "Geleceğin Teknolojisi, Bugünün Çözümleri",
        "heroSubtitle": "Destek Otomasyon, endüstriyel otomasyon alanında yenilikçi ve güvenilir çözümler sunar.",
        "aboutTitle": "Hakkımızda",
        "aboutText": "Destek Otomasyon, sektördeki derin tecrübesi ve uzman kadrosuyla, müşterilerinin verimliliğini artıran, maliyetlerini düşüren ve üretim süreçlerini optimize eden anahtar teslim otomasyon projeleri geliştirmektedir. Endüstri 4.0 prensiplerini benimseyerek, işletmenizi geleceğe taşıyoruz.",
        "whyUsTitle": "Neden Destek Otomasyon?",
        "whyUsSubtitle": "Sektördeki farkımızı yaratan ve projelerinizde başarıyı garantileyen temel değerlerimiz.",
        "whyUsCard1Title": "Uzman Kadro ve Tecrübe",
        "whyUsCard1Text": "Alanında uzman mühendis kadromuz ve 15 yılı aşkın sektör tecrübemizle projelerinize değer katıyoruz.",
        "whyUsCard2Title": "Kalite ve Güvenilirlik",
        "whyUsCard2Text": "Uluslararası standartlara uygun, uzun ömürlü ve güvenilir otomasyon çözümleri sunmayı taahhüt ediyoruz.",
        "whyUsCard3Title": "7/24 Teknik Destek",
        "whyUsCard3Text": "Proje teslimi sonrası da yanınızdayız. Olası sorunlara karşı 7/24 kesintisiz teknik destek sağlıyoruz.",
        "statsProject": "Tamamlanan Proje",
        "statsCustomer": "Mutlu Müşteri",
        "statsExperience": "Yıllık Tecrübe",
        "ctaTitle": "Projenizi Hayata Geçirmeye Hazır mısınız?",
        "ctaSubtitle": "Fikrinizi, projenizi veya ihtiyacınızı bizimle paylaşın, size özel çözümler üretelim.",
        "ctaButton": "Teklif Alın",
        "footerTitle": "Destek Otomasyon",
        "footerText": "Endüstriyel otomasyon ve Endüstri 4.0 çözümleriyle işletmenizi geleceğe taşıyoruz. Verimlilik ve teknoloji odaklı mühendislik hizmetleri.",
        "footerLinksTitle": "Hızlı Linkler",
        "footerContactTitle": "İletişim",
        "footerAddress": "Gebze, Kocaeli, Türkiye",
        "footerRights": "© 2025 Destek Otomasyon. Tüm Hakları Saklıdır.",
        "servicesPageTitle": "Sunduğumuz Çözümler",
        "servicesPageSubtitle": "İşletmenizin ihtiyaçlarına özel, verimlilik odaklı mühendislik çözümleri.",
        "service1Title": "PLC & SCADA Sistemleri",
        "service1Text": "Süreçlerinizi güvenilir PLC ve kullanıcı dostu SCADA arayüzleri ile tasarlıyor, programlıyor ve devreye alıyoruz.",
        "service2Title": "Robotik Otomasyon",
        "service2Text": "Montaj, kaynak, taşıma ve paketleme gibi operasyonlar için anahtar teslim robotik hücre çözümleri sunuyoruz.",
        "service3Title": "Görüntü İşleme Sistemleri",
        "service3Text": "Kalite kontrol, ölçüm ve ürün ayrıştırma süreçlerinizi, yüksek hassasiyetli kamera sistemleri ile otomatikleştiriyoruz.",
        "service4Title": "Servo & Hareket Kontrol",
        "service4Text": "Yüksek hız ve hassasiyet gerektiren uygulamalarınız için servo motor ve sürücü sistemleri ile çözümler üretiyoruz.",
        "service5Title": "Pano İmalatı ve Montajı",
        "service5Text": "Projenize özel, uluslararası standartlara uygun MCC, PLC ve otomasyon panolarının imalatını ve saha montajını yapıyoruz.",
        "service6Title": "Revizyon & Modernizasyon",
        "service6Text": "Mevcut makine ve sistemlerinizi son teknoloji otomasyon ürünleri ile modernize ederek verimliliğini artırıyoruz.",
        "projectsPageTitle": "Referans Projelerimiz",
        "projectsPageSubtitle": "Farklı sektörlerde hayata geçirdiğimiz, verimlilik ve inovasyon odaklı otomasyon çözümlerimiz.",
        "project1Title": "Otomotiv Montaj Hattı Robotizasyonu",
        "project1Text": "Tam otomatik montaj hattı ile %30 üretim artışı ve %99.9'un üzerinde hassasiyet sağlandı.",
        "projectButton": "Proje Detayı",
        "project2Title": "Gıda Paketleme & Kalite Kontrol",
        "project2Text": "Görüntü işleme ve robotik kollarla tam otomatik paketleme ve kalite kontrol sistemi.",
        "project3Title": "Lojistik Akıllı Depo Otomasyonu",
        "project3Text": "AGV'ler ve otomatik tasnif sistemleri ile sipariş hazırlama süresinde %60 azalma.",
        "project4Title": "Beyaz Eşya Fabrikası SCADA Sistemi",
        "project4Text": "Tüm üretim verilerinin anlık izlendiği, raporlandığı ve analiz edildiği merkezi SCADA sistemi.",
        "contactPageTitle": "Bizimle İletişime Geçin",
        "contactPageSubtitle": "Projelerinizi görüşmek ve teklif almak için bize ulaşın.",
        "contactFormTitle": "Bize Yazın",
        "contactFormName": "Adınız Soyadınız *",
        "contactFormEmail": "E-posta Adresiniz *",
        "contactFormSubject": "Konu",
        "contactFormMessage": "Proje Detaylarınız / Mesajınız *",
        "contactFormButton": "Mesajı Gönder",
        "contactInfoTitle": "İletişim Bilgileri",
        "contactInfoAddress": "Destek Otomasyon A.Ş.<br>Teknoloji Cad. No: 12/A<br>Gebze, Kocaeli/Türkiye"
    },
    "en": {
        "navHome": "Home",
        "navServices": "Services",
        "navProjects": "Projects",
        "navContact": "Contact",
        "phone": "+90 539 957 1333",
        "heroTitle": "Technology of the Future, Solutions for Today",
        "heroSubtitle": "Destek Otomasyon provides innovative and reliable solutions in the field of industrial automation.",
        "aboutTitle": "About Us",
        "aboutText": "With its deep industry experience and expert staff, Destek Otomasyon develops turnkey automation projects that increase the efficiency of its customers, reduce their costs, and optimize their production processes. By adopting Industry 4.0 principles, we carry your business into the future.",
        "whyUsTitle": "Why Destek Otomasyon?",
        "whyUsSubtitle": "Our core values that make a difference in the industry and guarantee success in your projects.",
        "whyUsCard1Title": "Expert Staff and Experience",
        "whyUsCard1Text": "We add value to your projects with our expert engineering staff and over 15 years of industry experience.",
        "whyUsCard2Title": "Quality and Reliability",
        "whyUsCard2Text": "We are committed to providing long-lasting and reliable automation solutions that comply with international standards.",
        "whyUsCard3Title": "24/7 Technical Support",
        "whyUsCard3Text": "We are with you even after project delivery. We provide uninterrupted 24/7 technical support for potential problems.",
        "statsProject": "Completed Projects",
        "statsCustomer": "Happy Customers",
        "statsExperience": "Years of Experience",
        "ctaTitle": "Ready to Bring Your Project to Life?",
        "ctaSubtitle": "Share your idea, project, or need with us, and we will create custom solutions for you.",
        "ctaButton": "Get a Quote",
        "footerTitle": "Destek Otomasyon",
        "footerText": "We carry your business into the future with industrial automation and Industry 4.0 solutions. Efficiency and technology-oriented engineering services.",
        "footerLinksTitle": "Quick Links",
        "footerContactTitle": "Contact",
        "footerAddress": "Gebze, Kocaeli, Turkey",
        "footerRights": "© 2025 Destek Otomasyon. All Rights Reserved.",
        "servicesPageTitle": "Solutions We Offer",
        "servicesPageSubtitle": "Efficiency-oriented engineering solutions tailored to your business needs.",
        "service1Title": "PLC & SCADA Systems",
        "service1Text": "We design, program, and commission your processes with reliable PLCs and user-friendly SCADA interfaces.",
        "service2Title": "Robotic Automation",
        "service2Text": "We offer turnkey robotic cell solutions for operations such as assembly, welding, handling, and packaging.",
        "service3Title": "Vision Systems",
        "service3Text": "We automate your quality control, measurement, and product sorting processes with high-precision camera systems.",
        "service4Title": "Servo & Motion Control",
        "service4Text": "We produce solutions with servo motor and drive systems for your applications requiring high speed and precision.",
        "service5Title": "Panel Manufacturing & Assembly",
        "service5Text": "We manufacture and install MCC, PLC, and automation panels in accordance with international standards, specific to your project.",
        "service6Title": "Revision & Modernization",
        "service6Text": "We increase the efficiency of your existing machines and systems by modernizing them with the latest automation technology.",
        "projectsPageTitle": "Our Reference Projects",
        "projectsPageSubtitle": "Our efficiency and innovation-oriented automation solutions implemented in different sectors.",
        "project1Title": "Automotive Assembly Line Robotization",
        "project1Text": "Achieved a 30% increase in production and over 99.9% precision with a fully automated assembly line.",
        "projectButton": "Project Details",
        "project2Title": "Food Packaging & Quality Control",
        "project2Text": "Fully automatic packaging and quality control system with vision processing and robotic arms.",
        "project3Title": "Logistics Smart Warehouse Automation",
        "project3Text": "60% reduction in order preparation time with AGVs and automatic sorting systems.",
        "project4Title": "White Goods Factory SCADA System",
        "project4Text": "A central SCADA system where all production data is monitored, reported, and analyzed in real-time.",
        "contactPageTitle": "Contact Us",
        "contactPageSubtitle": "Contact us to discuss your projects and get a quote.",
        "contactFormTitle": "Write to Us",
        "contactFormName": "Your Name *",
        "contactFormEmail": "Your Email Address *",
        "contactFormSubject": "Subject",
        "contactFormMessage": "Your Project Details / Message *",
        "contactFormButton": "Send Message",
        "contactInfoTitle": "Contact Information",
        "contactInfoAddress": "Destek Otomasyon Inc.<br>Technology St. No: 12/A<br>Gebze, Kocaeli/Turkey"
    }
};