const translations = {
    "tr": {
        "navHome": "Anasayfa",
        "navServices": "Hizmetler",
        "navProjects": "Projeler",
        "navContact": "İletişim",
        "phone": "+90 539 957 1333",
        "heroTitle": "Geleceğin Teknolojisi, Bugünün Çözümleri",
        "heroSubtitle": "Destek Otomasyon, endüstriyel otomasyon alanında yenilikçi ve güvenilir çözümler sunar.",
        "heroBtnQuote": "Hemen Teklif Alın",
        "heroBtnServices": "Hizmetlerimiz",
        "aboutTitle": "Hakkımızda",
        "aboutText": "Destek Otomasyon, sektördeki derin tecrübesi ve uzman kadrosuyla, müşterilerinin verimliliğini artıran, maliyetlerini düşüren ve üretim süreçlerini optimize eden anahtar teslim otomasyon projeleri geliştirmektedir. Endüstri 4.0 prensiplerini benimseyerek, işletmenizi geleceğe taşıyoruz.",
        "aboutFeature1": "Profesyonel Ekip",
        "aboutFeature2": "7/24 Destek",
        "aboutFeature3": "Garantili Çözümler",
        "aboutFeature4": "Yüksek Teknoloji",
        "aboutBtnMore": "Daha Fazla Bilgi",
        "whyUsTitle": "Neden Destek Otomasyon?",
        "whyUsSubtitle": "Sektördeki farkımızı yaratan ve projelerinizde başarıyı garantileyen temel değerlerimiz.",
        "whyUsCard1Title": "Uzman Kadro ve Tecrübe",
        "whyUsCard1Text": "Alanında uzman mühendis kadromuz ve 15 yılı aşkın sektör tecrübemizle projelerinize değer katıyoruz.",
        "whyUsCard2Title": "Kalite ve Güvenilirlik",
        "whyUsCard2Text": "Uluslararası standartlara uygun, uzun ömürlü ve güvenilir otomasyon çözümleri sunmayı taahhüt ediyoruz.",
        "whyUsCard3Title": "7/24 Teknik Destek",
        "whyUsCard3Text": "Proje teslimi sonrası da yanınızdayız. Olası sorunlara karşı 7/24 kesintisiz teknik destek sağlıyoruz.",
        "statsProject": "Tamamlanan Proje",
        "statsCustomer": "Mutlu Müşteri",
        "statsExperience": "Yıllık Tecrübe",
        "ctaTitle": "Projenizi Hayata Geçirmeye Hazır mısınız?",
        "ctaSubtitle": "Fikrinizi, projenizi veya ihtiyacınızı bizimle paylaşın, size özel çözümler üretelim.",
        "ctaButton": "Hemen İletişime Geçin",
        "footerTitle": "Hakkımızda",
        "footerText": "Endüstriyel otomasyon ve Endüstri 4.0 çözümleriyle işletmenizi geleceğe taşıyoruz. Verimlilik ve teknoloji odaklı mühendislik hizmetleri.",
        "footerLinksTitle": "Hızlı Linkler",
        "footerContactTitle": "İletişim",
        "footerAddress": "Gebze, Kocaeli, Türkiye",
        "footerRights": "© 2025 Destek Otomasyon. Tüm Hakları Saklıdır.",
        "newsletterTitle": "E-Bülten",
        "newsletterText": "Yeniliklerden haberdar olmak için e-bültenimize kayıt olun.",
        "newsletterPlaceholder": "E-posta adresiniz",
        "servicesPageTitle": "Hizmetlerimiz",
        "servicesPageSubtitle": "Sizin için sunduğumuz profesyonel çözümler",
        "service1Title": "PLC Programlama",
        "service1Text": "Endüstriyel süreçlerinizi otomatize etmek için gelişmiş PLC yazılım çözümleri.",
        "service2Title": "Robotik Sistemler",
        "service2Text": "Üretim hattınıza hız ve hassasiyet katan robotik entegrasyonlar.",
        "service3Title": "SCADA Sistemleri",
        "service3Text": "Tesisinizin verilerini anlık izleyin ve kontrol edin.",
        "service4Title": "Makine Otomasyonu",
        "service4Text": "Özel makine imalatı ve modernizasyonu için otomasyon desteği.",
        "service5Title": "Enerji Verimliliği",
        "service5Text": "Enerji tüketimini optimize eden akıllı sistemler.",
        "service6Title": "Bakım ve Servis",
        "service6Text": "Sistemlerinizin kesintisiz çalışması için periyodik bakım hizmetleri.",
        "projectsPageTitle": "Projelerimiz",
        "projectsPageSubtitle": "Başarıyla tamamladığımız referans projelerimiz",
        "project1Title": "Otomotiv Montaj Hattı",
        "project1Text": "Tam otomatik montaj hattı PLC ve SCADA entegrasyonu.",
        "projectButton": "Detayları İncele",
        "project2Title": "Gıda Paketleme Tesisi",
        "project2Text": "Yüksek hızlı paketleme ve etiketleme sistemi.",
        "project3Title": "Lojistik Depo Otomasyonu",
        "project3Text": "Akıllı raf sistemleri ve otomatik stok takibi.",
        "project4Title": "Beyaz Eşya Fabrikası",
        "project4Text": "Robotik boyama ve kalite kontrol ünitesi.",
        "contactPageTitle": "İletişim",
        "contactPageSubtitle": "Bizimle iletişime geçmekten çekinmeyin",
        "contactFormTitle": "Bize Mesaj Gönderin",
        "contactFormName": "Ad Soyad",
        "contactFormEmail": "E-posta Adresi",
        "contactFormSubject": "Konu",
        "contactFormMessage": "Mesajınız",
        "contactFormButton": "Gönder",
        "contactInfoTitle": "İletişim Bilgileri",
        "contactInfoAddress": "Gebze, Kocaeli, Türkiye",
        "contactAddressTitle": "Adres",
        "contactPhoneTitle": "Telefon",
        "contactEmailTitle": "E-posta"
    },
    "en": {
        "navHome": "Home",
        "navServices": "Services",
        "navProjects": "Projects",
        "navContact": "Contact",
        "phone": "+90 539 957 1333",
        "heroTitle": "Future Technology, Today's Solutions",
        "heroSubtitle": "Destek Otomasyon provides innovative and reliable solutions in industrial automation.",
        "heroBtnQuote": "Get a Quote",
        "heroBtnServices": "Our Services",
        "aboutTitle": "About Us",
        "aboutText": "With its deep industry experience and expert staff, Destek Otomasyon develops turnkey automation projects that increase efficiency, reduce costs, and optimize production processes. We carry your business into the future with Industry 4.0 principles.",
        "aboutFeature1": "Professional Team",
        "aboutFeature2": "24/7 Support",
        "aboutFeature3": "Guaranteed Solutions",
        "aboutFeature4": "High Technology",
        "aboutBtnMore": "Learn More",
        "whyUsTitle": "Why Destek Otomasyon?",
        "whyUsSubtitle": "Our core values that create our difference in the sector and guarantee success in your projects.",
        "whyUsCard1Title": "Expert Team & Experience",
        "whyUsCard1Text": "We add value to your projects with our expert engineering team and over 15 years of industry experience.",
        "whyUsCard2Title": "Quality & Reliability",
        "whyUsCard2Text": "We commit to providing long-lasting and reliable automation solutions that comply with international standards.",
        "whyUsCard3Title": "24/7 Technical Support",
        "whyUsCard3Text": "We are with you after project delivery. We provide uninterrupted 24/7 technical support for potential issues.",
        "statsProject": "Completed Projects",
        "statsCustomer": "Happy Customers",
        "statsExperience": "Years of Experience",
        "ctaTitle": "Ready to Realize Your Project?",
        "ctaSubtitle": "Share your idea, project, or need with us, and we will create custom solutions for you.",
        "ctaButton": "Contact Us Now",
        "footerTitle": "About Us",
        "footerText": "We carry your business into the future with industrial automation and Industry 4.0 solutions. Efficiency and technology-oriented engineering services.",
        "footerLinksTitle": "Quick Links",
        "footerContactTitle": "Contact",
        "footerAddress": "Gebze, Kocaeli, Turkey",
        "footerRights": "© 2025 Destek Otomasyon. All Rights Reserved.",
        "newsletterTitle": "Newsletter",
        "newsletterText": "Sign up for our newsletter to stay informed about innovations.",
        "newsletterPlaceholder": "Your email address",
        "servicesPageTitle": "Our Services",
        "servicesPageSubtitle": "Professional solutions we offer for you",
        "service1Title": "PLC Programming",
        "service1Text": "Advanced PLC software solutions to automate your industrial processes.",
        "service2Title": "Robotic Systems",
        "service2Text": "Robotic integrations adding speed and precision to your production line.",
        "service3Title": "SCADA Systems",
        "service3Text": "Monitor and control your facility's data instantly.",
        "service4Title": "Machine Automation",
        "service4Text": "Automation support for special machine manufacturing and modernization.",
        "service5Title": "Energy Efficiency",
        "service5Text": "Smart systems that optimize energy consumption.",
        "service6Title": "Maintenance & Service",
        "service6Text": "Periodic maintenance services for the uninterrupted operation of your systems.",
        "projectsPageTitle": "Our Projects",
        "projectsPageSubtitle": "Our successfully completed reference projects",
        "project1Title": "Automotive Assembly Line",
        "project1Text": "Fully automatic assembly line PLC and SCADA integration.",
        "projectButton": "View Details",
        "project2Title": "Food Packaging Facility",
        "project2Text": "High-speed packaging and labeling system.",
        "project3Title": "Logistics Warehouse Automation",
        "project3Text": "Smart shelf systems and automatic stock tracking.",
        "project4Title": "White Goods Factory",
        "project4Text": "Robotic painting and quality control unit.",
        "contactPageTitle": "Contact",
        "contactPageSubtitle": "Feel free to contact us",
        "contactFormTitle": "Send Us a Message",
        "contactFormName": "Name Surname",
        "contactFormEmail": "Email Address",
        "contactFormSubject": "Subject",
        "contactFormMessage": "Your Message",
        "contactFormButton": "Send",
        "contactInfoTitle": "Contact Information",
        "contactInfoAddress": "Gebze, Kocaeli, Turkey",
        "contactAddressTitle": "Address",
        "contactPhoneTitle": "Phone",
        "contactEmailTitle": "Email"
    }
};